doc.type.html
script
html
head
utf8
viewport content=width=device-width, initial-scale=one>
title covidstrings5secondround bracket
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
padding 
text align center
filename=covidstrings5secondround.js
highestremainingseed =(greatest remaining num value in covid strings list)
lowest remaining seed =(lowest remaining num value in covid strings list)
intermediateseed1=(first middle remaining value in covid strings list)
intermediateseed2=(second middle remaining value in covid strings list)
createround(teams)
round = document.createelement(div);
round.classlist.add(round);
for (let i =zero ; i < teams.length; i += two) {
round.appendchild(creatematchup(teams[i],teams[i + one]));
return round;
create matchup(intermediate seed2 versus intermediateseed1)
create matchup (lowest remaining seed versus highest remaining seed)    
matchup.covid strings seed list.add(matchup)
bracket.append child(matchup)
java util.scanner
java.util
questions[]questions={
question20
question21
question22
question23
question24
question25
question26
question27
collections.shuffle(arrays.aslist(questions)
private string getblanks(int numberofblanks)
char[] chars = new char[numberofblanks]
arrays.fill chars 
return new string chars
bracket.innerhtml = html;
advancingteams=slice(current teams)
result= declarewinner(matchup1)
if intermediate seed1 score>=forty:
console.log(intermediate seed1 wins)
else:
console.log(intermediate seed2 wins)
result= declarewinner(matchup2)
if  highest remaining seed score >=forty:
cnsole.log(highest remaining seed wins)
else:
console.log(lowest remaining seed wins)
return filename
        
