doc. type. html
script
html
head
filename=covidstrings5 championship game.js
championship game=(highest and lowest remaining seeds ) 
low seed=lowest remaining seed
high seed =highest remaining seed 
round div = covid strings5 championship round
matchupclassname=matchup
matchup div innerhtml=[team low seed versus team high seed]
round div.appendchild(matchup div)
bracket.appendchild(round div)
advancingteam=(current teams)
java util.scanner
java.util
questions[]questions={
question28
question29
question30
question31
question32
question33
question34 
collections.shuffle(arrays.aslist(questions)
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
myclass=newmyclass(concatenated) 
return category
if category==math problem:
prompt
log
else:
select from multiple choice
import syntax 
substring(start,end)
userin.multiplechoice
if selectedanswer==correct answer:
return true
else:
return false
declare winner
if team high seed score>sixty=:
console.log(team high seed wins covid strings5)
else:
console.log(team low seed wins covid strings5)
return filename
