doc. type. html
script
html
head
filename=covidstrings5secondround.js
highestremainingseed =(greatest remaining num value in covid strings list)
lowest remaining seed = (lowest remaining num value in covid strings list)
intermediateseed1=(first middle remaining value in covid strings list)
intermediateseed2=(secondmiddleremainingvalueincovidstringslist)
createround(teams)
round = document.createelement(div);
round.classlist.add(round);
for (let i =zero ; i < teams.length; i += two) {
round.appendchild(creatematchup(teams[i],teams[i + one]));
return round;
create matchup(intermediateseed2versusintermediateseed1)
create matchup (lowest remaining seed versus highest remaining seed)    
matchup.covid strings seed list. add(matchup)
bracket.append child(matchup)
java util.scanner
java.util
questions[]questions={
question20
question21
question22
question23
question24
question25
question26
question27
collections.shuffle(arrays.aslist(questions)
private string getblanks(int numberofblanks)
char[] chars = new char[numberofblanks]
arrays.fill chars 
return new string chars
advancingteams=slice(current teams)
bracket.innerhtml = html;
result= declarewinner(team1 score, team2 score)
if intermediate seed1 score>=fourty:
console.log(intermediate seed1 wins)
else:
console.log(intermediate seed2 wins)
advancingteams=slice(currentteams)
declarewinner 
if  highest remaining seed score >=fourty:
cnsole.log(highest remaining seed wins)
else:
console.log(lowest remaining seed wins)
if intermediate seed 1 score>=fourty:
console.log(intermediate seed 1 wins)
else:
console.log(intermediate seed 2 wins)
return filename
        
