<doc.type html>
<script>
filename= covid strings5 background.js
java.awt graphics
img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div> 
audio=new audio (audio_file mp3)
audio.play 
jbutton random button
new jbutton(set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add (color.panel, border layout. center )
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener(){
override 
public void actionperformed(actionevent e){
random r= newrandom();
colorpanel.setbackground(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener(){
override 
public void actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this,))
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static void main(string [] args){
jframe f = new covid strings5()
f.set title(covid strings5)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblScore>zero</label>
score=zero
if(mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if(mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerhtml=score
private j button next button=new jbutton(next)
nextbutton add.actionlistener(this)
public void actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one, b:two, c:three, d:four, e:five, f:six, g:seven, h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
return filename
